Repository schmittjoh/serializer, pull requests merged in 2018-05, with the labels that each got.

#946 Simplify deep group exclusion strategy
  src/Exclusion/GroupsExclusionStrategy.php
  tests/Serializer/BaseSerializationTest.php
  tests/Serializer/JsonSerializationTest.php
  tests/Serializer/xml/groups_advanced.xml
Labels: BC Break

#944 Allow inline lists and maps
  src/JsonSerializationVisitor.php
  src/Metadata/ClassMetadata.php
  src/Metadata/Driver/AnnotationDriver.php
  src/Metadata/Driver/XmlDriver.php
  src/Metadata/Driver/YamlDriver.php
  src/Metadata/PropertyMetadata.php
  tests/Fixtures/FirstClassListCollection.php
  tests/Fixtures/FirstClassMapCollection.php
  tests/Metadata/Driver/BaseDriverTest.php
  tests/Metadata/Driver/xml/FirstClassListCollection.xml
  tests/Metadata/Driver/xml/FirstClassMapCollection.xml
  tests/Metadata/Driver/yml/FirstClassListCollection.yml
  tests/Metadata/Driver/yml/FirstClassMapCollection.yml
  tests/Serializer/JsonSerializationTest.php
Labels: enhancement

#949 Revert https://github.com/schmittjoh/serializer/pull/113
  src/Serializer.php
Labels: RFC

#951 Fix DoctrineObjectConstructor deserialization with naming strategies
  src/JMS/Serializer/Construction/DoctrineObjectConstructor.php
  tests/Fixtures/Doctrine/IdentityFields/Server.php
  tests/Serializer/Doctrine/ObjectConstructorTest.php
Labels: To Merge, bug
