Repository schmittjoh/serializer, pull requests merged in 2019-04, with the labels that each got.

#1069 Expose and test GroupsExclusionStrategy::getGroupsFor()
  src/JMS/Serializer/Context.php
  src/JMS/Serializer/Exclusion/GroupsExclusionStrategy.php
  tests/Exclusion/GroupsExclusionStrategyTest.php
Labels: enhancement

#1068 add options property to XmlDeserializationVisitorFactory and XmlDeserializationVisitor, propagate defined value from factory to simplexml_load_string call
  src/Visitor/Factory/XmlDeserializationVisitorFactory.php
  src/XmlDeserializationVisitor.php
Labels: Missing Tests, enhancement

#1071 Revert v2 nested groups and release 3.0
  README.md
  UPGRADING.md
  composer.json
  doc/cookbook/exclusion_strategies.rst
  src/Exclusion/GroupsExclusionStrategy.php
  tests/Exclusion/GroupsExclusionStrategyTest.php
  tests/Serializer/JsonSerializationTest.php
  tests/Serializer/xml/groups_advanced.xml
Labels: backwards-incompatible

#1076 Do not throw exception when visiting null in custom handler
  src/GraphNavigator/SerializationGraphNavigator.php
  tests/Serializer/BaseSerializationTest.php
Labels: bug

#1031 Fix for failing doctrine object constructor on embeddable class
  src/Construction/DoctrineObjectConstructor.php
  tests/Fixtures/Doctrine/XmlMapping/JMS.Serializer.Tests.Fixtures.Doctrine.Embeddable.BlogPostSeo.dcm.xml
  tests/Serializer/Doctrine/ObjectConstructorTest.php
Labels: bug
