Repository schmittjoh/serializer, pull requests merged in 2020-03, with the labels that each got.

#1169 do not hide Exceptions from custom handlers but correctly handle null
  src/GraphNavigator/SerializationGraphNavigator.php
  tests/Serializer/GraphNavigatorTest.php
Labels: enhancement

#1175 Handle discriminator groups
  src/Metadata/ClassMetadata.php
  tests/Fixtures/Discriminator/Serialization/Entity.php
  tests/Fixtures/Discriminator/Serialization/ExtendedUser.php
  tests/Fixtures/Discriminator/Serialization/User.php
  tests/Serializer/BaseSerializationTest.php
  tests/Serializer/JsonSerializationTest.php
  tests/Serializer/xml/user_discriminator.xml
  tests/Serializer/xml/user_discriminator_array.xml
  tests/Serializer/xml/user_discriminator_extended.xml
Labels: bug

#1174 test serializing entity that uses Discriminator and extends some base…
  tests/Fixtures/Discriminator/Serialization/Entity.php
  tests/Fixtures/Discriminator/Serialization/ExtendedUser.php
  tests/Fixtures/Discriminator/Serialization/User.php
  tests/Serializer/BaseSerializationTest.php
  tests/Serializer/JsonSerializationTest.php
  tests/Serializer/xml/user_discriminator.xml
  tests/Serializer/xml/user_discriminator_array.xml
  tests/Serializer/xml/user_discriminator_extended.xml
Labels: Failing Test
